spring.application.name=HealthCare_Backend

# Database configuration
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/healthcare_database}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mdnasique@123}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect





spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://illajbook.database.windows.net:1433;databaseName=free-sql-db-7009111;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mdnasique@illajbook}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:illajbook@123}

spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.microsoft.sqlserver.jdbc.SQLServerDriver}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT:org.hibernate.dialect.SQLServerDialect}



server.port=${PORT:8081}




## Razor pay API keys

razorpay.key_id=${RAZORPAY_KEY_ID:rzp_test_SZXxQegIwL6YbV}
razorpay.key_secret=${RAZORPAY_KEY_SECRET:j3RTYPNc6P4B5H08j5lJlS75}




#for mail


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:nasiquejahangir000@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:wkdd ntvy xssk tycg}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
