spring.application.name=HealthCare_Backend

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_database?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mdnasique@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080




## Razor pay API keys
razorpay.key_id= rzp_test_SZXxQegIwL6YbV
razorpay.key_secret= j3RTYPNc6P4B5H08j5lJlS75
